baseurl: http://macdfree.github.io
permalink: /:year-:month-:day/:title.html

paginate: 5
paginate_path: "/page:num"

markdown: kramdown

feed: /atom.xml

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from